name: tbd

on:
  issues:
    types:
      - opened

  workflow_dispatch:


jobs:
  
  my_job:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Wordle:')

    steps:
      - uses: actions/checkout@v2

      - name: Run a dummy command
        run: ls

      - name: Check working ENV
        run: |
          echo $REPOSITORY_OWNER

      - name: Setup Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Play wordle
        env:
          KEY: ${{ secrets.FERNET_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          pip -q install -r requirements.txt
          python main.py
      - name: commit and push changes baby
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}

        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${ISSUE_TITLE} by ${{ github.event.issue.user.login }}"
          git push
      
      - name: Check
        run: echo "congratulations... i guess"
