name: tbd

# Controls when the workflow will run
on:
  issues:
    types:
      - opened

  workflow_dispatch:

env:
  KEY: ${{ secrets.FERNET_KEY }}

jobs:
  
  my_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a dummy command
        run: ls
      
