name: tbd

# Controls when the workflow will run
on:
  issues:
    types:
      - opened

  workflow_dispatch:

env:
  WORD: ${{ secrets.CURRENT }}

jobs:
  
  my_job:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a dummy command
        run: ls

      # Runs a set of commands using the runners shell
      - name: Run some more commands
        run:
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: print environment variables to check
        env:
          NEXT: CERTI
        run:
          python check.py
      - name: set next word
        run:
          echo GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          gh secret set CURRENT < secret.txt
